# -*- coding: utf-8 -*-
"""Web Scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TWLYRJmZdoEXcJJ71mRcPNGTQGHaJ1ZC
"""

pip install bs4

pip install requests

#importing library 
import requests
from bs4 import BeautifulSoup
url='https://pricebaba.com/microwaves'

#checking the website response for accessing the data
response=requests.get(url)
response

#Parsing 
website=BeautifulSoup(response.text)
website

micro=website.select('.ellips-line-ell-2')

micro

micro_name=[]
for item in micro:
    micro_name.append(item.text)
    link="https://pricebaba.com"+item["href"]

micro_name

price=website.select('.d-block .txt-al-c')

price

micro_price=[]
for item in price:
  micro_price.append(item.text)

micro_price

vfm= website.select('.vfm__scr')

vfm

vfm_score=[]
for item in vfm:
  vfm_score.append(item.text)

vfm_score

import pandas as mb

web=mb.DataFrame(micro_name,columns=['Microware Oven Name'])

web

web['Price']=micro_price

web

web['VFM Score']=vfm_score

web

